# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

pool: Self

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'DockerHubConn'
        repository: 'asethori/weatherapi'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'

- stage: ARM template
  displayName: Deploy resource
  jobs:
  - job: Creation
    displayName: Creation
    steps: 
      - task:
       

- stage: Deploy
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    steps: 
      - task: AzureWebAppContainer@1
        inputs:
          azureSubscription: 'Azure subscription 1(457b89a8-82bc-4337-a34c-dff14982f42d)'
          appName: 'weatherapitesting'
          deployToSlotOrASE: true
          resourceGroupName: 'tfmainrg'
          slotName: 'production'
          containers: 'asethori/weatherapi:$(Build.BuildId)'