# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

pool: Linux

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    steps:
    - task: SonarQubePrepare@5
      inputs:
        SonarQube: 'NewSonar'
        scannerMode: 'MSBuild'
        projectKey: 'TerraformTest_TerraformTest_AYS1oC6BaQpvc62GU2Ez'
        projectName: 'terraformTest'
    - task: Docker@2
      inputs:
        containerRegistry: 'DockerHubConn'
        repository: 'asethori/weatherapi'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'

    - task: SonarQubeAnalyze@5

    - task: SonarQubePublish@5
      inputs:
        pollingTimeoutSec: '300'